var fs = require("fs");
var path = require("path");
var Sequelize = require("sequelize");
var env = process.env.NODE_ENV || "development";
var config = require(path.join(__dirname, '..', 'config', 'config.json'))[env];
var sequelize = new Sequelize(config.database, config.username, config.password, config);
var db = {};

db.sequelize = sequelize;
db.Sequelize = Sequelize;

db.frag = require('../models/frag.js')(sequelize, Sequelize);
db.game = require('../models/game.js')(sequelize, Sequelize);
db.match = require('../models/match.js')(sequelize, Sequelize);
db.player = require('../models/player.js')(sequelize, Sequelize);
db.round = require('../models/round.js')(sequelize, Sequelize);
db.team = require('../models/team.js')(sequelize, Sequelize);
db.tournament = require('../models/tournament.js')(sequelize, Sequelize);
db.user = require('../models/user.js')(sequelize, Sequelize);
db.weapon = require('../models/weapon.js')(sequelize, Sequelize);
db.news = require('../models/news.js')(sequelize, Sequelize);
db.comment = require('../models/comment.js')(sequelize, Sequelize);

//Relations
db.player.belongsTo(db.team);
db.team.hasMany(db.player);
db.player.belongsTo(db.weapon, {foreignKey: 'weapon_id'});
db.weapon.hasMany(db.player, {foreignKey: 'weapon_id'});
db.tournament.belongsTo(db.team, {foreignKey: 'winner_id'});
db.team.hasMany(db.tournament, {foreignKey: 'winner_id'});
db.match.belongsTo(db.team, {foreignKey: 'team1_id', as: 'first_team'});
db.team.hasMany(db.match, {foreignKey: 'team1_id', as: 'first_matches'});
db.match.belongsTo(db.team, {foreignKey: 'team2_id', as: 'second_team'});
db.team.hasMany(db.match, {foreignKey: 'team2_id', as: 'second_matches'});
db.match.belongsTo(db.team, {foreignKey: 'winner_id', as: 'win_team'});
db.team.hasMany(db.match, {foreignKey: 'winner_id'});
db.match.belongsTo(db.tournament, {foreignKey: 'tournament_id'});
db.tournament.hasMany(db.match, {foreignKey: 'tournament_id'});
db.game.belongsTo(db.match, {foreignKey: 'match_id'});
db.match.hasMany(db.game, {foreignKey: 'match_id'});
db.game.belongsTo(db.player, {foreignKey: 'mvp_id'});
db.player.hasMany(db.game, {foreignKey: 'mvp_id'});
db.round.belongsTo(db.game, {foreignKey: 'game_id'});
db.game.hasMany(db.round, {foreignKey: 'game_id'});
db.round.belongsTo(db.team, {foreignKey: 'winner_id'});
db.team.hasMany(db.round, {foreignKey: 'winner_id'});
db.round.belongsTo(db.player, {foreignKey: 'mvp_id'});
db.player.hasMany(db.round, {foreignKey: 'mvp_id'});
db.frag.belongsTo(db.round, {foreignKey: 'round_id'});
db.round.hasMany(db.frag, {foreignKey: 'round_id'});
db.frag.belongsTo(db.player, {foreignKey: 'killer_id'});
db.player.hasMany(db.frag, {foreignKey: 'killer_id'});
db.frag.belongsTo(db.weapon, {foreignKey: 'weapon_id'});
db.weapon.hasMany(db.frag, {foreignKey: 'weapon_id'});
db.news.belongsTo(db.user, {foreignKey: 'user_id'});
db.user.hasMany(db.news, {foreignKey: 'user_id'});
db.comment.belongsTo(db.user, {foreignKey: 'user_id'});
db.user.hasMany(db.comment, {foreignKey: 'user_id'});
db.comment.belongsTo(db.news, {foreignKey: 'news_id'});
db.news.hasMany(db.comment, {foreignKey: 'news_id'});

module.exports = db;
